### ISSUE TITLE
Default branch called now "main" in Github

### ISSUE THREAD

**Issue by rotzaff** [ioBroker/ioBroker.js-controller#1073]
Ich habe ein neues Repo angelegt und der default branch heißt "main" 

Ich habe dies zunächst mit dem Github-Desktop Programm gemacht und anschließend auf Github selbst getestet.

Ich konnte dadurch keine Repos von Github auf den ioBroker installieren - ich erhielt die Fehlermeldung unten.
Als ich ein neuen branch erstellt habe mit dem Namen "master" konnte ich ohne Problem den Adapter von Github in den ioBroker laden. 

$ ./iobroker url "https://github.com/rotzaff/ioBroker.smartmusicplayer"
Info: Can not get current GitHub commit, we remember master branch only. Status: 422 (No commit found for SHA: master)
install https://github.com/rotzaff/ioBroker.smartmusicplayer/tarball/master
NPM version: 6.14.6
npm install https://github.com/rotzaff/ioBroker.smartmusicplayer/tarball/master --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code E404
npm
 ERR! 404 Not Found - GET https://codeload.github.com/rotzaff/ioBroker.smartmusicplayer/legacy.tar.gz/masternpm ERR! 404 npm ERR! 404  'https://github.com/rotzaff/ioBroker.smartmusicplayer/tarball/master' is not in the npm registry.npm 
ERR! 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR! 404 npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-10-31T15_39_37_543Z-debug.log
ERROR: host.raspberrypi Cannot install https://github.com/rotzaff/ioBroker.smartmusicplayer/tarball/master: 1
ERROR: process exited with code 25

**Comment by foxriver76** [comment]
For GitHub, we could use the official API, via GET `https://api.github.com/repos/user/repo_name`, the JSON response also includes an attribute `default_branch`

**Comment by AlCalzone** [comment]
The problem is that JS-Controller tries to store which commit is being installed. I see multiple ways of doing that:
1. Get the `default_branch` from `https://api.github.com/repos/user/repo_name`, then retrieve the commit from `https://api.github.com/repos/user/repo_name/commits/default_branch`
2. Use the first commit from `https://api.github.com/repos/user/repo_name/commits` (array!) , which [defaults](https://developer.github.com/v3/repos/commits/#parameters) to the `default_branch`
3. Execute a git command to find it, here's an example for JS-Controller, which includes the default branch and sha:
```
$ git ls-remote --symref https://github.com/iobroker/ioBroker.js-controller HEAD
ref: refs/heads/master  HEAD
3edc464c005e284e7961de25818ae9fa2e75ff6b        HEAD
```

After we know that, let npm do the work:
```
npm i user/repo_name#sha
```
