### ISSUE TITLE
sendTo will not reject / fail if instance does not exist

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.js-controller#1079]
Hi there,

I'm bulk requesting with sendTo (https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L5457) in the following way (using `allSettled`):
```
new Promise((resolve, reject) => socket.sendTo('getEnabledDPs', null, 'history.0', (err, state) => err ? reject(err) : resolve(state))),
new Promise((resolve, reject) => socket.sendTo('getEnabledDPs', null, 'influxdb.0', (err, state) => err ? reject(err) : resolve(state))),
new Promise((resolve, reject) => socket.sendTo('getEnabledDPs', null, 'sql.0', (err, state) => err ? reject(err) : resolve(state)))
```

My challenge is that when an adapter instance does not exist, I will not receive an answer. Currently I'm addressing this by setting a timeout, but depending on the time of the request / loading time, etc. this may lead to wrong behavior.

Could you implement a rejection in case the receiving instance does not exist? Thanks!

**Comment by Apollon77** [comment]
And what if the instance ist currently simply not running? We would also need to reject there.

because of the "non-central" approach in iobroker there is nothing happening on js-controller level with "sendTo" requests. The controller only reacts on messages that are send to himself. Each other adapter instance reacts on his own messages. This means ... a message which is sent to an offline or non-existing instance will simply be published but not consumed by anyone - so aso noone else cn reject it ...

So only way is "expect a response within 5s and it is does not come then it is not existing.
Else each adapter needs to know all other system instances to do this check ... and this makes simply no real sense ...

My opinion ... others? ;-)

**Comment by foxriver76** [comment]
The method will also never call a callback if no specific instance is specified, because then multiple publishes could be performed, and thus a cb would be called multiple times. We could check the system.adapter... object for existence, but then it could still be, that the instance is not running (could we check) or not running properly. So only thing working would be to use a timeout in adapter.js or leave it as it is..
