### ISSUE TITLE
Feature Request: Auto-Update option for Adapters

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.js-controller#1261]
Hi,

adoption of new adapter versions currently is currently like this:

First week after release: 30-50%
2-4 weeks after release: 50-70%
Month later: ???

Some users still run beta versions which are a few month old.

Idea is now:

Integrate an option for automatic updates of Adapters

* Only when running on stable repo
* On new installations this option is enabled by default
* Only minor versions are automatically upgraded, major versions have often breaking changes
* Automatic random update 1-5 days after new version

The benefits:

* This will make it easier for the users to stay "up to date"
* Breaking changes by producers (e.g. in API, functionallity) will be fixed faster (e.g. Alexa Adapter)
* More users will have new functions and also bug fixes (Sentry)
* Old versions which are unsupported, may produce dissatisfaction for the user and Sentry errors will be gone
* Randomized updates over time prevent undiscovered problems for a bigger group of users after minutes 

Regards, Ralf

**Comment by DutchmanNL** [comment]
> * On new installations this option is enabled by default

in addition a news item would be interesting or warning that auto-update is disabled ?



> * Only minor versions are automatically upgraded, major versions have often breaking changes

minor and patch, Major.Minor.Patch



> * Breaking changes by producers (e.g. in API, functionallity) will be fixed faster (e.g. Alexa Adapter)

Remark : Developer is responsible to manage there versions properly, breaking changes must have a major version increase.
This means a little extra workload when new versions are released to stable (code review ?)

addition : How to handle deprecated packages, I can image a kind of force update or warning in the admin that current version is not supported anymore as I am as dev can deprecated versions on NPM

**Comment by foxriver76** [comment]
I have mixed feelings about this, for some, it may be useful, however, it can break something w/o really noticing, because of various reasons. Unfortunately, devs sometimes introduce breaking changes without increasing major versions. npm sometimes fails and can even destroy the module in edge cases, now the user won't be aware, because he didn't trigger the update itself. I guess there are more things that can go wrong which I am not considering right now.

On the other hand, I understand your pros. But I wouldn't let this functionality default to "enabled". If there are many problems coming up, this will be upsetting for many users making a bad sentiment around ioBroker. We could implement the feature and people can actively activate it. If the feedback of this feature is positive for some time, we could think about letting it default to "enabled". Personally, I wouldn't turn such a feature on.

**Comment by gaudes** [comment]
@DutchmanNL : I mean for examples breaking changes by Amazon in the API for Echo Devices, which breaks the adapter. Then Apollon has to create very fast a new version. By auto-update some users will not even notice the error.

@foxriver76 : Good point. We can create an entry in io-package.json. So the developer has to allow to participate in auto-update. When enabling, he acknowledge the function and the impact of this feature.
In the first version we can leave the default to disabled. When the feature works as designed, we can discuss again.

**Comment by DutchmanNL** [comment]
> @foxriver76 : Good point. We can create an entry in io-package.json. So the developer has to allow to participate in auto-update. When enabling, he acknowledge the function and the impact of this feature.
> In the first version we can leave the default to disabled. When the feature works as designed, we can discuss again.

I like this approach, but also the remark of @foxriver76 
We should make a decision if this option is enabled by default at all, to do that we have to mitigate the risk.

My suggestion would be to have a proper coding practice for versioning documented, and indeed by setting the flag in io-package the developer indicates to be in line with the Major.Minor.Patch version principle.

By that we keep the responsibility at the developer, doing that in code review is almost undoable

**Comment by Apollon77** [comment]
Latest ideas:
* define if only patch or patch+minor updates
* add a exclusion list of adapters NOT to update
* works in stable and latest repo

**Comment by AlCalzone** [comment]
I would prefer an **opt in** approach, per adapter. This way a user can decide where the risk is worth it and where not.

**Comment by Apollon77** [comment]
But which user will understand that ?  When douing this you need to add that to the "instance installation dialog", else noone will remember it :-(

**Comment by AlCalzone** [comment]
Or in the instances list, as an extra toggle. I'm just thinking: what's worse UX?
An outdated adapter because the user didn't find the auto-update function or an adapter that breaks and in turn leaves the user's heating cold while he is on holiday.

**Comment by Azathoth88** [comment]
Is there any progress here yet? I would welcome an auto update.

Breaking Changes" were mentioned in the discussion. Let's have an idea:
Would it be conceivable that the developer could disable the auto-update for such cases?

The breaking change version could get a special flag.
If the flag exists, the version can only be triggered manually.

Otherwise I like to ask for a workaround at this point.
Currently I have a WhatsApp sent to me when an update is ready.
Is there alternatively the possibility for a JavaScript / Blockly for the AutoUpdate?

**Comment by mcm1957** [comment]
I'm maybe a little late - but here's my comment:

- I would suggest that autoupdate is DISABLED by default. It would be fine, that the user is informed about the autoupdate feature rewgularly, i.e. by a log, by a banner at admin, at first login after restart, etc.

- If the autoupdate is implemented for other repositories than stable I would stromgly recommend that every change of the respository disabled the feature or issues a confirmation pop up. Otherwise it would be dangaroius as one could have enabled autoupdate using stable repo and does nozt remember when switchign to latest for any reason. And faster than he imaginzes several adapter would have been lifted to latest ...

- selective enabling / disabling per adapzter should only be discussed as a soft ob "freeze". If one has to enable autoupdate per adapter the number of users doing any autzoupdate would be very very small I guess.

- autoupdate should be spread at least abouzt one or two wees - I would suggest 1 month to avoid that too many users are upgraded in case of an error. Maybe (but that would be an extra effort) the user could select if he wanst to be an early updater or a lts user with later updates

- the suggestion to do a review during stable update is in my oppinion impossible. One could do a quick check - but a full codereview would be too timeconsuming - in addition to the follow up discussions with the developer if and whta to change...


Could I ask, what the current decisions for implementation are?
Whats planned?

**Comment by foxriver76** [comment]
> * I would suggest that autoupdate is DISABLED by default. It would be fine, that the user is informed about the autoupdate feature rewgularly, i.e. by a log, by a banner at admin, at first login after restart, etc.

We currently plan a two step activation, which means, you need to configure it on adapter level (`none` will be default), then you can configure `none, `patch`, `minor`, or even `major`. Additioaly, it needs to be activated for each repository, this is not implemented but I am thinking about, activating it on upgrade of controller for the current repository if nothing set yet. Admin should then display a dropdown per instance, if activated for the current repo. Else dropdown should be disabled and at least on hover, say it is deactivated for curren repo.

> * If the autoupdate is implemented for other repositories than stable I would stromgly recommend that every change of the respository disabled the feature or issues a confirmation pop up. Otherwise it would be dangaroius as one could have enabled autoupdate using stable repo and does nozt remember when switchign to latest for any reason. And faster than he imaginzes several adapter would have been lifted to latest ...

I think above mentioned concept answers the question and keeps it in mind.

> * selective enabling / disabling per adapzter should only be discussed as a soft ob "freeze". If one has to enable autoupdate per adapter the number of users doing any autzoupdate would be very very small I guess.

We think about a popup on manual upgrade, where it asks you to configure auto upgrade. I would strongly recommend, to disable it by default. After some "field tests", we can of course think about changing this, however, better start defensive. 

> * autoupdate should be spread at least abouzt one or two wees - I would suggest 1 month to avoid that too many users are upgraded in case of an error. Maybe (but that would be an extra effort) the user could select if he wanst to be an early updater or a lts user with later updates

We have to think about that, e.g. what happens if an adapter is updated very regulary, you will never get an auto update then. I also tend, to say, that 1 month is a pretty long time frame. 

> * the suggestion to do a review during stable update is in my oppinion impossible. One could do a quick check - but a full codereview would be too timeconsuming - in addition to the follow up discussions with the developer if and whta to change...

Not sure, where this suggestion comes from, for me it is also not realistic, it is really just about the technical feature here for me. No change in another process.
