### ISSUE TITLE
Define Tiers for some default adapters

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1298]
* Logic adapter tier 1
  * javascript
  * scenes
  * node-red

* Should we start Notification adapter in tier 1 or 3? 1 to get all notifies from logic when data come in or?
  * telegram
  * pushover
  * pushsaver
  * whatsapp

* Should we start data logging adapter as tier 1 or 3?
  * history/sql/influxdb

* Should we start "allows to contzrol stuff" adapters in tier 1 (before controlling adapters) or in tier 3 (after them)?
  * text2command
  * web
  * simpe-api
  * iot

* Device adapters: tier 2
  * hm-rega/hm-rpc
  * sonoff
  * mqtt
  * shelly
  * hue
  * zigbee
  * zwave2

**Comment by foxriver76** [comment]
IMHO it makes no sense to start adapters like vis when control adapters are not working, otherwise you would press a button and the logic behind it may could not be triggered, because adapter not started yet. So I would start stuff like telegram and history in 1, but web vis etc in 3.

I've already added Tiers to hm-rega, hm-rpc, javascript, hue

**Comment by foxriver76** [comment]
Done?

**Comment by Apollon77** [comment]
Still in progress ... 20-40 adapters to do

**Comment by foxriver76** [comment]
still?

**Comment by Apollon77** [comment]
maybe some less but I decided to do other stuff then this right now ... lets close here
