### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.js-controller#1377]
Is it planned toconvert controller to typescript?

Maybe we could setup a typescript build, and do it file after file, everytime someone has time. We could allow js files in the source so we don't need to convert everything in one go.

I started this years ago: https://github.com/ioBroker/ioBroker.js-controller/pull/448

I think today, nearly every javascript development is done in typescript.

**Comment by Apollon77** [comment]
> I think today, nearly every javascript development is done in typescript.

I complely do not think that! :-)

In fact we had that discussion in the past already in the core developer group. In fact one developer is form with TypeScript, the other three Codre devs more likely not at the moment. This would then slow down the development and end up in "mixed code styles".
In this topic wer decided to still progres sin modularizations nd cleanup to get the project itself more modular and better organized first before we might start thinking about that topic again in the future.

@AlCalzone @foxriver76 @GermanBluefox Correct?

**Comment by jogibear9988** [comment]
In our company we switched our Application from Plain Javascript to TS, and this increased productivity a lot. 
I don't see where this could slow down.
It mostly would help to get the project more modular, cause you see errors early.

https://serokell.io/blog/why-typescript

Every big company is using it. Google (Bspw. Angular, LIT), Github (https://github.com/github/catalyst), Microsoft show me one bigger Javascript Project in the last few years not using Typescript.

**Comment by UncleSamSwiss** [comment]
> > I think today, nearly every javascript development is done in typescript.
> 
> I complely do not think that! :-)

Multiple big projects (like Sentry) switched to TypeScript in the past years. All of them reported better quality, less issues and better code maintenance.

Saying that you want to clean up code **before** switching to TypeScript seems completely counterintuitive. I know it would be a big step, but many of the past (and probably also future) bugs could have been prevented by using TypeScript.

As @jogibear9988 said: there is no need to change the entire code base, and it would definitely help if we did it step by step.

I would be interested in the opinion of @AlCalzone

**Comment by Apollon77** [comment]
Honestly this discussion is odd. Three of the main developers from core are not having any experience in Typescript , and when I see Bluefox and me also not "even more spare time" to get familiar enough to be productive (and this exactly is the reason why it works in a company  - you GET the time there!).

And so my "less productivity" argument stays because 4-3 developers makes ONE developer left that can work productively on controller and would also need to drive such a change project ... So unless we do not have some more developers also interested in eighter stepping up and participate actively on js-controller or support taking care of the roughly 150 Orga and Community adapters in maintenance I see no way to change the time situation at the moment. I have another role in my company so it would not be that meaningful to try to start learning Typescript that way (but yes also we are on TypeScript because some developer drove it ... also with Effects as bigger entry-hurdles for new developers on the project ...)
So this was very honest (and yes a bit striking  too), but thats reality in my eyes.

**Comment by AlCalzone** [comment]
I have mixed feelings about this. On one hand I think the hurdle is perceived to be bigger than it actually is. Sure, there are some things to learn, but 95% of what the ioBroker codebase does can be typed with primitives and some simple interfaces. Additionally, you need a config file, a build task and that's basically it. 

If you ask me, the break-even point spent on time learning TS comes **very** quickly. https://github.com/zwave-js/zwavejs2mqtt was rewritten to TypeScript in a few days - which also found a bunch of bugs. I assisted a bit with very advanced topics, but I can count the questions I got on one hand. The author had never used TS before in his life.

Regarding developer productivity:
How does typing a variable or function reduce productivity? When implementing something, you already know if something should be a number or a string or a boolean - now it just gets written down.

Furthermore I think there are some points that are overlooked with that argument.

1. TypeScript **is documentation**. Having everything typed correctly would prevent a lot of questions like "What does this function expect and return?" which usually requires us to go to the implementation and try to understand the sometimes very confusing code. Especially when you're not working in the codebase very often (i.e. like me), most of the time is spent figuring out **how the hell** stuff works. Time that wouldn't be necessary if you could look at the types and see "function xyz accepts ABC and returns XYZ, I can do zyx with it". You also don't have to think whether a `+` concatenates two strings or adds up two numbers.

2. TypeScript **reduces the cognitive workload** in understanding the code. When used in `strict` mode, it knows how the type of variables changes throughout the code. You don't have to read an entire function to comprehend whats in a variable at any given line or if it can be undefined.

3. Also, as I like to preach, TypeScript **prevents you from forgetting** things. You can't simply change a function signature and change only 2 out of 3 call sites. Especially if the third is in some obscure location, you don't have to release a beta and find a bug through the power of multiple testers. TypeScript will tell you directly.

4. TypeScript **removes an entire class of errors**, namely those where the code is inconsistent with itself. The developer time can be spent on making features work correctly instead of making the code correct.

5. TypeScript **helps refactoring**. Because it understands how the code belongs together, it can rename all instances of a method for example, again preventing us from forgetting half of it.

(Side note: I don't understand why needing a build task for frontend code is okay but needing a build task for backend code seems to be a counter-argument)

---

On the other hand, TypeScript requires discipline, it requires code to be written in a certain way which is easier to comprehend btw (see 2.). In short it requires everyone to be on board with it.

Our codebase is in a notoriously TS-unfriendly style. Variables that change their meaning and type throughout their lifetime, tons of overloads (alone 6 for [getForeignObjects](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a18f6bd993626257e1abdf4fded9bae501234e72/types/iobroker/index.d.ts#L592-L603), not counting trailing optional parameters) for which functions need more code for figuring out the parameters than actual implementation, etc... All of which makes introducing TypeScript harder. Typing these overloads in JSDoc is impossible btw.

I've tried the half-assed approach of introducing good type declarations into the JS code at least twice now (controller and db repo). Every time I had to find workarounds for the code style or ended up with semi-correct types and it took me so long that I had to basically start over when I got around to it again.

---

Having said that I still think doing it would be beneficial.  IMO the best way to get familiar with TypeScript is learning by doing, which doesn't even take much time when you're starting from scratch [e.g. with a new adapter \**cough* *cough*\*](https://github.com/Apollon77/ioBroker.ph803w).

Now that we're modularizing JS-Controller into separate repos like the db repo, socket-client, etc. we have a great opportunity to do it on a small scale. In these we can start from the ground up: convert files that don't import anything, then those that import the converted files etc. Eventually everything will be modular enough that moving JS-Controller over wouldn't be such a mammoth task.

**Comment by AlCalzone** [comment]
Objective discussion aside: One needs to be a bit masochistic to maintain such a complex project **without** TS if you ask me 🤐

**Comment by Apollon77** [comment]
I know the pro parts (and have no issue with the build step ... don't care) and I'm not against TS tbh, dont get me wrong here!

There also is a personal topic and feelings in my way.

But the "commitment to it" is a big thing (at least for me as partially perfectionist). If we do it then we all need to be commited to it and we need "support" from people that know it (My personal experience with TS so far was that I wanted to do stuff 3 times and all three I needed support to get the typings right ... yes maybe I did not chose the easy things, but thats life) ... so I invested ore time in searching for the "How" then I would have needed to do it in JS. That's a hurdle for me personally because it does not *feel* productive time investment. And with my current topic list I have then topics where I can invest my time better. All of this is personal topics and a lot of feelings ... right.
Maybe once I'm out of that "too much on the plate" I'm more relaxed for "new things" and also find the time for them, Maybe I try with a new adapter ... who knows

Starting "mixed", ending up in FIles bein partially TS "annotated" and JS make then no sense for the professional side and perfectionist. So, when then right and then driven by "really doing it".

But so long as one of the two main driving devs on js-controller (With BF being on "Frontend" and AlCalzone being reviewer and with zwave project - no problem, just reality!) I just can say: You need to accept that.

So long I more think together with @foxriver76 about how to better restructure the controller, as @AlCalzone said so that we maybe have smaller pieces.
One idea on my plate for 3.4+, maybe could be really making a monorepo out of it with modules for cli, adapter, core/main tools, after that we could start (given TS knowledge/support and available resources) chosing a small one as a first mover ...

**Comment by Apollon77** [comment]
PS/OT: @AlCalzone socket.client was extracted from adapter-react when I remember correctly (and BTW should we link it in socketio adapter readme or make a new example that uses that there?

**Comment by jogibear9988** [comment]
i would create a pull req. for adapter-react wich removes the js code and uses the socket-client when a npm package of socket-client is created.
i had fixed the ts errors in the build script, but now there is an error in another step

**Comment by jogibear9988** [comment]
I don't think it would make sense to convert it inone go, that means no other development could be donde during this time. But allow mixed ts/js code, so everytime someone has time, a part could be converted. 
I see only advantages of typescript, but i will not find time to become on of the lead developers of controller, so it's okay for me.
But i think if you are an external and need to got into some code you don't know, it's much easier in typescript as in plain javascript.

**Comment by foxriver76** [comment]
From a rational point of view there is no huge con of TS. However, as @Apollon77 already stated, you have to keep in mind, that ioBroker is a super modular project and every adapter, plugin, etc. can be written in the language of your choice (currently if the compiled code is JS). And this is basically the same for the controller and the majority of controller devs for now want to develop this adapter in plain nodejs. Thus, I don't really see the problem for other ioBroker developers. And yes this decision is very subjective. Live and let live.

**Comment by Apollon77** [comment]
>  But i think if you are an external and need to got into some code you don't know, it's much easier in typescript as in plain javascript.

I still do not see that as reality ... and was also not finding any statistics that prove that and also do not want to start such a basic disusssion about "which flavor is more". :-)

**Comment by AlCalzone** [comment]
> the majority of controller devs for now want to develop this adapter in plain nodejs [...]. Live and let live.

... and they'll have to live with us nagging about TypeScript every now and then 🤣.

All I can say is: Try it on a simple project, get familiar with it. There comes a point when it clicks and you don't want to give it up anymore. I'll be waiting 😎
