### ISSUE TITLE
setBinaryStateAsync needs namespace and throws permission error

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.js-controller#1425]
Trying to set a state with the type file I ran into following issues:
1. Passing ownly the id like `device.channel.stateName` after calling `await createStateAsync()` for the exact same ID results in Error Object not exist: `Object.maybeCallbackWithError (C:\Program Files\iobroker\DevUmgebung\node_modules\iobroker.js-controller\lib\tools.js:2252:17) at Immediate.checkStates (C:\Program Files\iobroker\DevUmgebung\node_modules\iobroker.js-controller\lib\adapter.js:7839:34) at runCallback (timers.js:706:11) at tryOnImmediate (timers.js:676:5) at processImmediate (timers.js:658:5)`
2. Extending the id to contain namespace as well (like `adapter.instance.device.channel.state`) results in a permission error: `permissionError at Object.maybeCallbackWithError (C:\Program Files\iobroker\DevUmgebung\node_modules\iobroker.js-controller\lib\tools.js:2252:17) at Immediate.adapterObjects.getObject (C:\Program Files\iobroker\DevUmgebung\node_modules\iobroker.js-controller\lib\adapter.js:5181:38) at runCallback (timers.js:706:11) at tryOnImmediate (timers.js:676:5) at processImmediate (timers.js:658:5)`
`Permission error for user "system.user.admin" on "ring.0.doorbell_xxxx.Snapshot.snapshot": setState`

Additional info to 2: For debugging purposes I allowed writing in the statecommon, which didn't resolve the issue.

According to @Apollon77 the behaviour of `setBinaryStateAsync` might be more of `setForeignBinaryStateAsync`

Edit: Node.js v14.17.4, js-controller 3.3.15

**Comment by theimo1221** [comment]
Indeed: https://github.com/ioBroker/ioBroker.js-controller/blob/7ebd3811c5201fe07d21c00375002274d4c76545/lib/adapter.js#L7948
`validateId(id, true, options);`

`setBinaryState` validates the id as it is a foreign one.

**Comment by theimo1221** [comment]
Even with this PR I locally get `Object does not exist` so there might be another issue

**Comment by foxriver76** [comment]
The binary states methods  are missing the admin workaround https://github.com/ioBroker/ioBroker.js-controller/blob/287743063dc849bbccbbe557f22e0e7b59445f20/lib/adapter.js#L6631

Will fix it.

**Comment by theimo1221** [comment]
@foxriver76 regarding this statement of yours:
> But setBinaryState expects a foreign id, so why validate a own ns id..

We have functions like `setState` and `setForeignState`, why should `setBinaryState` -without further information/clarification- be for foreign states?
In my opionion it'd be much clearer if it's this gets renamed to `setForeignBinaryState` and a new function `setBinaryState` get's created. Due to downwards compatibility we might need to come up with a different approach, but generally you'd agree that this function is a pitfall for adapter developer, wouldn't you?

**Comment by foxriver76** [comment]
Yes, generally I agree. But as you mentioned you cannot just change the behavior and break a bunch of adapters. Controller is a lot about backward compatibility, as hard as it is as a dev.

It's also a little bit confusing, because my statement is in your PR (not in this issue) and your PR basically changes a check which will of course not make the function handle non foreign ids - theres more to it.

**Comment by theimo1221** [comment]
>  theres more to it.
Thus I canceled the PR.


>, as hard as it is as a dev.

We'd have the option to add a function `setOwnBinaryState` and add proper description to the type defintion/jsdoc of the `setBinaryState` function to warn about it beeing for foreign ids.
Additionally we could rename the parameter `id` to `foreignId` which by itself gives more clarity.

**Comment by theimo1221** [comment]
`* @param {string} id of state`

We could change this one too, directly in adapter.js without colliding with normal naming convention

**Comment by foxriver76** [comment]
Yes, we can do so when fixing the issue, however we should wait until all PRs are merged, because we will restructure the controller and this needs a short PR stop unfortunately. Don't want to stop your enthusiasm. ;-) 

Problem is, normal dev won't look in the controller code and the JSdoc is not shown to anyone besides us. Thus, we have created the typings (e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/iobroker/index.d.ts), which is basically what the adapter devs sees in his IDE as hints, autocompletion etc.
