### ISSUE TITLE
Question: UnitTesting own functions?

### ISSUE THREAD

**Issue by schoenr79** [ioBroker/ioBroker.js-controller#1523]
Hello ioBroker community,

does somebody has a tip for me, how to unit test its own js functions, created within a js-controller instance. Is that generally possible?
I want to ensure that my funcs are running stable over time, and i only want to get notified in case of an error.

cheers
Roland

**Comment by foxriver76** [comment]
I assume you mean unit tests for an adapter. Then, https://github.com/ioBroker/testing is the way to go.

**Comment by schoenr79** [comment]
Actually i mean my own script functions created to use inside ioBroker. 
As i see, it's possible to install additional npm modules on the adapter instance. So i thought it may be poissible to add a simple unit test module to be able to des my global functions.

**Comment by foxriver76** [comment]
Basically you could add mocha and chai to your script instance, however the problem comes up, that every script runs in a separate sandbox and you can only access methods inside the same script (except from global ones).

So this is not a working scenario yet, you could discuss this use case in an enhancement issue in the script engine adapter. Basically it is an interesting idea.
