### ISSUE TITLE
Default Log Level not respected on instance creation

### ISSUE THREAD

**Issue by MikeW83** [ioBroker/ioBroker.js-controller#1634]
I have a fresh installation of ioBroker and set the default log level to "warn" in the system settings. But every adapter is created with "info". I have to correct it manually to "warn". I don't want the log file to be flooded with info messages.

Is this a bug or a feature?

**Comment by Apollon77** [comment]
@MikeW83 Thank you for reporting the issue ... it seems there was a typo and thats why this setting had no effect. Sorry. js.controller 4.0 which will go into testing soon will have the fix for it. For 3.3 you need to work around by settings loglevel manually via admin please (available in expert mode)
