### ISSUE TITLE
NodeJS 4 end-of-life in April

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#164]
According to https://github.com/nodejs/Release NodeJS 4 will enter the end-of-life stage in April. Which means it will no longer get security fixes after that.

I know we dropped support for 0.x very late, but maybe we should prepare the transition to NodeJS 6?

**Comment by Apollon77** [comment]
The idea would be again to be conservative :-(

So in April we add Info in admin when Node 4 is used and we need to make sure to have a good upgrade docu. 
We could start to decline new installations with node 4 via iobroker Package. This is easy and a good balance in my eyes. 

Then we need another 3 months (?!) before we can remove Support officially. 

I think Bluefox has statistics about nodejs usage .. maybe we can get a graph on one of the stat pages ;-)

I planned in March to add node 9 to all tests.

**Comment by AlCalzone** [comment]
Not sure if I'd wait until april to add the information, but I agree a good documentation for the upgrade is necessary before we do that.
How's the npm5 support btw? I've seen some commits mentioning it.

**Comment by Apollon77** [comment]
We currently only have a "iobroker only fully supports the following node versions, please update" message. SO we have nothing to tell "hey soon we will deprecate node 4" :-(

NPM5: It seems that we are affected by https://github.com/npm/npm/issues/17379 ... so wait for fix from them ... I still does not really found out why ... Windows can be because there we install one package from github, else only some rare adapters do this

**Comment by AlCalzone** [comment]
Wonder what they are doing over there... how's such a serious bug not fixed after months?!

**Comment by Apollon77** [comment]
Yes interesting ... it took me >1h to find that one because it was reported that often but it seems it took looong time to really figure out the reason ...

**Comment by Apollon77** [comment]
Ok, here my list of todos (proposal!!) to outphase 4.x as officially supported
* Communicate it in Forum, Facebook and all the other channels.
* With an Admin 3 release somewhen in May (or June?) we can remove it from officially supported list, so that nodejs 4.x users will get an Notify in Admin when they open it. What e do with Admin v2? Let it in?
* Testing should stay including nodejs 4 as long as users still use it (@GermanBluefox can we get some nodejs-usage-infos from installations on stats.html or such?)

**Comment by Apollon77** [comment]
Should we start something now more "officially"

**Comment by GermanBluefox** [comment]
I wanted to close this issue today too, but yes... we must to do something.
At least instructions how to update.
I suggest to update to node8 + npm 5.8.0

4 июн. 2018 г. 15:44 пользователь "Ingo Fischer" <notifications@github.com>
написал:

Should we start something now more "officially"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.js-controller/issues/164#issuecomment-394359468>,
or mute the thread

**Comment by Apollon77** [comment]
jepp, think too
