### ISSUE TITLE
When adapter process ist called with --install emit an install event instead of ready

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1894]
... parameter could be a callback to call when actions are done which then automatically triggers process shutdown, so also here devjust need to make sure to call callback when done.

We might need to check/adjust adapters:
* sayit
* vis-google-fonts
* vis

**Comment by mcm1957** [comment]
snmp uses --install too. Maybe more adapters use it to perform migration of config data.

When implementing a change please consider a fallback mechanism id adapters are not updated yet, i.e.
-) onInstall event handler exists - call it but do no longer call onReady (new functionality)
-) otherwise behave like now, simply call onReady

**Comment by Apollon77** [comment]
sure, if onInstallis not present the original behaviour is executed. But we will also inform devdlopers beforehand
