### ISSUE TITLE
Combine States and Objects

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.js-controller#203]
As in this [thread](https://forum.iobroker.net/viewtopic.php?f=24&t=14489) written, States can not exists without an related Object. So it is uneccessary to handle them sepperate when deleting Object or State. 

ToDo: 
- Remove delState from adapter.js
- delObject/delForeignObject has to delete states too

**Comment by Jey-Cee** [comment]
delState -> OK
delObject/delForeignObject -> OK

While testing this i found out that setState create's no Object related to the state.

**Comment by GermanBluefox** [comment]
setState cannot create object. It has no info about state

ср, 13 июн. 2018 г., 9:34 Jey-Cee <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Done?

**Comment by Jey-Cee** [comment]
Yes

**Comment by AlCalzone** [comment]
I just found out this causes the issue I describe here #268 . The reason for that is that I use `delState` because it used to delete the state **without** deleting the corresponding object.

The OP describes that __States can not exists without an related Object__. However this change is not entirely in line with this description. I think it is fair that deleting an object deletes the corresponding state. But deleting the state should not delete the object IMO.

Is it really necessary to delete the object when deleting the state? Or can we have the separation like this:
* `delState` => only deletes state (since objects can exist without states)  
* `delObject` => deletes the object and the state

**Comment by Apollon77** [comment]
After thinking I would see it like @AlCalzone ... delState should only clear the value (as it did before). I also see this as a needed functionality e.g. when restructuring states in an adapter and adding a new substructure under the nbame of a former state ... sometime you want to remove the value from such a new channel object or so ...

**Comment by Apollon77** [comment]
Also the method name contains the scope:
* setObject creates a new object with no or default value as state
* delObject removes both object and state
* setState only set state and returns error when object do not exist
* delState removes the state vlalue and returns error when object do not exist

(same for the *Foreign* methods)

I think this way it is understandable
