### ISSUE TITLE
Override of setTimeout / setInterval

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.js-controller#2047]
A adapter could use setTimeout (not the one from the controler), and forget to clear it on unload.

We could override the setTimeout to use our own implementation (wich could clean up), and internal use the original one.

CompactMode: 
We need to know wich adapter raised the setTimeout, this could be easy in synchronous code (we could store the name of the adapter we starting at the moment), but in asynchronous code, it would be hard.

Non Compact Mode:
I think for non compact mode, the whole thing is not really an issue, cause the process is killed anyway. But we still could use it to raise errors, so the developers know they do something wrong

**Comment by AlCalzone** [comment]
Patching globals doesn't seem like a good idea. Libraries may rely on behavior and break.

Also we already have `adapter.setTimeout` etc for this purpose.

**Comment by Apollon77** [comment]
Yes this was also my firth thought,  ut we wanted to get other opinions on it. But now we are three that have a bad feeling - aand it would not really help because problematic in compact mode because there all modules run without sandboxes or such ... so overriding would need to "remember" who set a timeout to stop the right ones if one compact mode instance ends - I checked the code .... I see no way ...

Thats why would close again

**Comment by Apollon77** [comment]
@AlCalzone The main discussion today was that not many developers know of adapter.setTimeout ... maybe we should enhance create adapter "default code block" with an example?

**Comment by jogibear9988** [comment]
and we also could override setTimeout and create a warning that it's not safe to use.

**Comment by jogibear9988** [comment]
> Patching globals doesn't seem like a good idea. Libraries may rely on behavior and break.
> 
> Also we already have `adapter.setTimeout` etc for this purpose.

You still could mimic the behavior...

**Comment by jogibear9988** [comment]
also most people don't use compact mode, so we could raise errors for specifc adapters
