### ISSUE TITLE
Execute npm as IoB User

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#217]
make it possible to execute "iobroker npm ....":
- in this case the npm command will be executed by js-controller as iobroker user.

create in `/opt/iobroker` the file "**npm**" that starts `iobroker npm .... --production --save --prefix /opt/iobroker`

**Comment by AlCalzone** [comment]
I think this command should internally execute the `npmCommand` method I'm preparing in my js-controller branch:
https://github.com/AlCalzone/ioBroker.js-controller/blob/tools-npmCommand/lib/tools.js#L1352
or maybe the `npmInstall` command directly:
https://github.com/AlCalzone/ioBroker.js-controller/blob/tools-npmCommand/lib/tools.js#L1459

That branch is not complete yet, but in order to keep things in once place, we should consolidate our efforts.

**Comment by Apollon77** [comment]
@AlCalzone still relevant when we have the new ACL and user stuff from new installer?

**Comment by AlCalzone** [comment]
Probably for those users where the ACL stuff fails. In general I would like a command to execute stuff as the iobroker user, e.g. `iobroker exec command...`
