### ISSUE TITLE
More Adapter development convenient functions

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#227]
I'm currently working on soef's Alexa Adapter and so got an insight in his soef library. While being strange in some regards the basic idea ist that he encapsulated some "things you always do" into that library.
While checking that and also thinking about my life as adapter developer I see several things I do "the same but new" for each adapter (or I copy code). So the idea would be to offer support for them in adapter class directly. Ideas could be:

1.) On adapter init you normally create a lot of objects (when not already contained in io-package) and most of the time I simply fire the calls and dont care about the asyncronity of things because do not really care - only cares when you later want to listen for objectChanges ... 
Normally you need to implement a task queue and the logic to process the queue to get the callback when everything is done. Idea would be to build in such a "object update queue" and a command to process the queue. Maybe only have new Methods like "setObjectNotExistsQueued" oder a queued-parameter to the existing methods.

2.) The current adapter concepts kind if "split" logic in the adapter code. We have one place to create needed objects (mostly in main or called from this) and a second place to react on changes to this object/state. The idea would be to add "trigger" callbacks as additional optional parameter to  all setObject* commands (plus a new registerChangeCallback) and offer a "One liner command" to execute the reigistered callback bsed on the ID. Biggest benefit is that you have object creation and "what should happen when It got changes" in one place (where you also maybe have other data that can be used in callback -context). This could make things easier

What do you think about that?

I will try to implement something "generic" in Alexa now also to see if it is really better, so we also could have code to discuss.

**Comment by AlCalzone** [comment]
I'm all for creating convenience methods for things that are common to adapter code, but...

**Regarding 1:**
If it's not necessary that the objects are created in a specific order, having async functions and using Promise.all would do the trick. Lets assume `setObjectNotExistsAsync` is a method that behaves just like `setObjectsNotExists`, but returns a Promise instead of accepting a callback. A method like this can be created with the `promisify` method [already in place](https://github.com/ioBroker/ioBroker.js-controller/blob/e0fa33b7c3e612804908d67cf689aa14bf4105ed/lib/tools.js#L1137). 
To create all objects and then do something, the following code would work:
```js
const queue = [
    setObjectNotExistsAsync("id1", obj1),
    setObjectNotExistsAsync("id2", obj2),
    // ...
];
// ^ -- here the creation process is started and an array of promises is remembered
// v -- this code waits for all promises to be fulfilled
Promise.all(queue)
    .then(() => {
        // do something when it's done
    })
    .catch((e) => {
        // handle the error
    })
;
```
Alternatively one can define the objects in an array and create the queue with the map function:
```js
const objects = [
{ _id: "obj1", /* ... */ },
{ _id: "obj2", /* ... */ },
{ _id: "obj3", /* ... */ },
// ...
];
const queue = objects.map(o => setObjectNotExistsAsync(o._id, o));
Promise.all(queue)
    .then(() => {
        // do something when it's done
    })
    .catch((e) => {
        // handle the error
    })
;
```

I think we should leverage the power Promises (and modern JavaScript in general) give us to handle async code. Therefore I prefer creating async versions of the adapter methods (or rather wrap them using `promisify`) and work with that.

If the objects have to be created in a specific order, there's also a [helper function](https://github.com/ioBroker/ioBroker.js-controller/blob/e0fa33b7c3e612804908d67cf689aa14bf4105ed/lib/tools.js#L1224) already implemented:
```js
const objects = [
{ _id: "obj1", /* ... */ },
{ _id: "obj2", /* ... */ },
{ _id: "obj3", /* ... */ },
// ...
];
// to have the process execute in a sequence we must return promise-returning functions. By doing so, `setObjectNotExists` is not immediately executed, but rather when it should be.
const queue = objects.map(o => {
    return () => setObjectNotExistsAsync(o._id, o);
});
// now we can execute the sequence and wait for the last one to finish
promiseSequence(queue)
    .then(() => {
        // do something when it's done
    })
    .catch((e) => {
        // handle the error
    })
;
```
