### ISSUE TITLE
Unhandled exception: Could not check object existence of e3dc-rscp.0.info in js-controller-common/lib/common/tools.js

### ISSUE THREAD

**Issue by git-kick** [ioBroker/ioBroker.js-controller#2408]
This was [reported by Sentry](https://ulrich-kick.sentry.io/issues/4379907545/).

**NB: this is the first time I am trying to hand over a Sentry-detected error to other developers - please give me advise if there is a more efficient way to do that, or in case it makes no sense to propagate such Sentry findings.**

The error was detected on some (not my) machine running adapter [e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp) which I developed. It was reported only once, so it seems to have quite special preconditions; I assume it has something to do with the broken connection mentioned in the report, so it may be caused by some network/timing situation.

I know the root cause may be a bug in my code (which I did not find yet), but I think an unhandled exception in the common lib should not occur anyway.

In case the [Sentry URL](https://ulrich-kick.sentry.io/issues/4379907545/) mentioned above is not easily accessible, I add a screenshot here:
![grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/8932938/6610505f-f03d-451a-be91-26faf701a080)

**Comment by Apollon77** [comment]
@git-kick Thank you for reporting. In this case the controller is the originator, but the issue relies in your adapter. The reason is that the database connection is closed and a "setObjectNotExists" was triggered.
This normally means that the adapter goit unloaded while he is stopping but some logic was still running after the unload callback was called. So check your adapter please when this could happen.

Interestingly this is your "onReady" method ... I would ignore the issue until it happens again.

**Comment by mcm1957** [comment]
The problem might be caused by using setState without either await or callback. Thus some setStates might be still in progress while the adapter already shuts down.

https://github.com/git-kick/ioBroker.e3dc-rscp/blob/4ab1556885ea271ddd0adbf19c42b5ecd95ec325/main.js#L1875

setState withou callback behaves asynchronous and returns a promise (as far as I know).
@Apollon77 please correct if I'm wrong

**Comment by git-kick** [comment]
OK thank you @Apollon77 and @mcm1957, I will have a close look at the onReady() method and try to avoid lagging operations.
