### ISSUE TITLE
[enhancement]: Make tier level more flexible

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.js-controller#2555]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Is it possible to add more flexibility to the tier level or the starting order of the adapters? (Similar to Proxmox) In Proxmox, you can, among other things, set delay times or timeouts.

Additionally, it would be interesting to have an option where you can use a checkbox to wait for all adapters in an tier level before proceeding to the next tier level.

### Why?

It would be useful to initially update or hold current data points from other adapters, and then use the updated data points in scripts, for example with the JavaScript adapter. In my case, I want the JavaScript adapter to start very last.

### How?

1. In the "admin adapter", in the Instances tab, more options for configuring the startup behavior of individual adapters, as described above.

2. The ability to configure in the global settings of the "admin adapter" the option to explicitly wait for the start of all adapters in an tier level before proceeding to the next one.

I think the controller must first be able to handle this so that the entire functionality can be implemented graphically in the admin adapter. Therefore, I've submitted a feature request in this repository.

**Comment by foxriver76** [comment]
This would need some additional redesign in nearly every adapter. Because we can only check that adapter ready handler has been called by controller, but eg JavaScript needs to start all activated scripts, hm-rega needs to poll all devices first etc.

This has the potential to delay instance starts significantly. And needs mentioned adapter specific adaptions + an adapter specific fail timeout if the ok status would never be sent back. 

Currently I think there is a hard wait of 2 seconds between instance starts, which pretty much ensures that ready is called. We could look into optimizing a bit here instead of the timeout heuristic but the main idea of this ticket would be something for the long run instead. 

Do you have another perspective on this @apollon77?

**Comment by pafade89** [comment]
@foxriver76 @Apollon77 

The effort is significant, as it will likely take time for all adapters to be updated. It would probably make sense to have an adapter compatibility check, which you typically do with major releases of a new JS controller version, right?

Could you also integrate the condition for adapter starts into your [adapter creator](https://github.com/ioBroker/create-adapter)?

Thank you and have a nice weekend.

**Comment by Apollon77** [comment]
In fact I would start discussing this topic with "real world use cases", because I miss these currently. Just that an enhanced concept would be possible in theory the question is still if it makes sense. I assume that I can use one hand to cound the users that know and use this concept for own orders ... so ... whats the exact usecase? 
Because else I would say: The current concept is flexible enough

**Comment by pafade89** [comment]
Hello, I didn't realize this feature is used very little. Now I understand that it's probably not worth the effort. Thank you for your thoughts and feedback.
