### ISSUE TITLE
[enhancement]: Additional protocol level

### ISSUE THREAD

**Issue by guitardoc** [ioBroker/ioBroker.js-controller#2645]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

Maybe there is a chance of getting an additional protocol level like critical or some such which records adapters dying etc. Some adapters send loads of protocol information within the error level leading to filling up the protocol file.

### Why?

See above

**Comment by mcm1957** [comment]
The requested enhancement is (in my oppion) a little bit misunderstanding here.

The original source of this issue is https://forum.iobroker.net/topic/73641/adapter-vom-protokoll-ausschlie%C3%9Fen
And there was the situation that an adapter creates a big number of errors. So the user wanted to block the adapter from storing level erroro logs (which is not possible cuurrently) but real fatal errors (crash) should be recorded anyway.

So the main enhancement request shoudl read: "allow to set logging to none or critical".

Personally I do not see a need to create an additional logging level available for adapters. The only point to be discussed would be if blocking error logs like ist is possible to block wanring, info, ... should be possible and hwo to deal with crashes in this case.

**Comment by Apollon77** [comment]
When adapter log too much as error whcih should not be error please give this feedback to the developer to adjust it. I assume just adding another loglevel will not achange any of these issues :-)

**Comment by foxriver76** [comment]
I don't think that one should block all error logs of an adapter just because he regularly get spammed by one. Errors are normally very important to be seen and not only in crash cases. Adapter could also still run but getting no data. We have a pretty strong opinion on this and basically the log is not like a visu which has to be nice and clean. The log is there to show you if things are getting wrong somewhere and disabling this completely should not be desireable.

So goal would really be to get it fixed in this specific adapter.

**Comment by foxriver76** [comment]
This is impossible to be configurable in controller. As said, the adapter developer should please fix this. ;-)

If an adapter is unmaintained for too long there will be more serious problems like this and we always have possibilities for such cases. However, this specific scenario is not critical. 

My last words on this: More log levels will just shift the problem for a while until the new max loglevel is misused and disabling is  no option.
