### ISSUE TITLE
[bug]: js controller works with >=18

### ISSUE THREAD

**Issue by Arcticon** [ioBroker/ioBroker.js-controller#2734]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Readme suggests that the js-controller works with node 16, but it does not:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/package.json#L6

**Comment by foxriver76** [comment]
The current latest and stable version of js controller work with node 16

**Comment by Apollon77** [comment]
@Arcticon If you have actual real problems with any 5.0.x version please post more details. This needs to run with Node.js 16 normally. Just the upcoming js-controller 6 will kick Node.js 16

**Comment by Arcticon** [comment]
@Apollon77 js-controller 5.0.20 (alpha) increased the minimum node version to 18:
https://github.com/ioBroker/ioBroker.js-controller/blob/v5.0.20-alpha.0-20240510-819f1976e/packages/controller/package.json#L6

**Comment by Apollon77** [comment]
So again ... whats exactly your problem? :)

**Comment by Arcticon** [comment]
https://github.com/UncleSamSwiss/ioBroker.loxone is/was using @dev for their integration tests.
@dev references 5.0.20-alpha (which is js-controller version 5) and that should start with node 16

I also think 5.0.20-alpha is not the correct way of labeling that version, because it points towards a 5.0.20 release.
6.0.0-alpha would be more suitable.

**Comment by foxriver76** [comment]
Integration tests are always running against dev controller. And yes for this it is true node 16 is not supported for testing anymore.
Please remove node 16 from tests that's all you have to do and is coming ground among the devs currently.

Regarding versioning you are right, the process is still being optimized and due to historic reasons there was no version bump to 6 yet and will only be when the first “official” alpha of 6 is released for testing. We will see if this will change in the future.

**Comment by Arcticon** [comment]
Im strongly against using @dev (which is always changing) for integration tests. This means that a rudimentary change can cause the pipeline to fail.

Im all for changing the process :)

**Comment by foxriver76** [comment]
The process isn’t something we decided in like 5 minutes it has developed and this is what made most sense to us to find problems with adapters early on before releasing a new controller and then needing to fix a lot of adapters.

**Comment by Apollon77** [comment]
@Arcticon I understand your thoughts and they were also brought up some weeks ago. In fact we try to keep a balance between 
* "the core developers know if any change breaks adapters" -because we else never get any test coverage with enough adapter to see this before a release
* "allowing us and developers see if an upcoming non-breaking change hs effects" - Adapter devs are/were very creative sometime and use core functions in unintended/unknown/undocumented ways - seeing this before a controller release is also good for the adapter devs to fix their usage
* "simplify all this" :-) (if we would let devs choose, noone woul use @dev ...)

In fact all this is to ensure the quality and compatibility of the js-controller as the main and central component of ioBroker. As @foxriver76 already stated this was iterated aleady several times and each solution has cons that are meehh .. so we decided for the "least problematic one" (because when we deprecate a node.js version most likely test frameworksand other deps - if kept up to date - were also alteady breaking that for testing) ...

if you still have thought about it you're welcome to put the topci on the next dev-meeting topic list and join us there for an in person discussion.

**Comment by Arcticon** [comment]
i understand all your concerns, but this is not a good practice at all.
lets say you are just maintaining your code and update a readme file. this means that you have to update your codebase to allow for a simple change.
iobroker already has the io-package.json to list all supported versions of the admin/js-controller dependency.
when an adapter specifies support for 2.0.0 to 5.0.19, then this means that the code works 100% for the specified range.
this would also be best practice, because it allows the iobroker UI to hide any adapters that are not "supported"/"tested" for the currently installed admin/js-controller.

you are trying to force up2date dependencies for something that people can abandon.
try to image a dev setup, lets say arch linux, where every update can break a system. would it be wise to develop on such a system? no, unless you are working with the latest changes.

i want to have a testing system where i can pinpoint to breaking changes and can isolate any variable that might cause my code to break.

on the other hand you are all correct in terms of "loxone adapter is out of date". im trying to help out and lets see where i can bring this.

**Comment by Apollon77** [comment]
>  2.0.0 to 5.0.19,

exactkly this 100% of the dependencies in io-package do not say ... They just define the lower bound which also makes sense because in most cases the controller tries to be backward compatible ... just node.js deprecations we mostly are forced to.

I also understand your pov and yes it is not "the most common way", but it is " the way with the most benefots for the project and the developers", but some downsides (basically once a year max when we deprecate a node.js version :-) ) ...

**Comment by Arcticon** [comment]
looks like we are on the same page anyways :)
thanks for the great down to earth discussion!
