### ISSUE TITLE
[bug]: js-controller update doesn' work on the Hosts page

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.js-controller#2884]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

After pressing the update button:
![image](https://github.com/user-attachments/assets/32b1c597-bb1c-4875-bfe7-f2bc96a3349d)

![image](https://github.com/user-attachments/assets/d85745bb-2d84-447e-a267-ede09eb9695b)

### Reproduction instruction

Press the button

### JS-controller version

6.0.9

### Node version

20.16.0

**Comment by foxriver76** [comment]
Too less information to say anything tbh. And is it really not working or just displaying the error, is controller stopped, is anything in log? …

**Comment by afuerhoff** [comment]
Proxmox Debian 12 LXC

Console: Nothing
Log:
![image](https://github.com/user-attachments/assets/235b1297-2540-4968-bc93-85601c104892)

**Comment by foxriver76** [comment]
And after the will upgrade itself logline nothing? And controller is not stopped?

**Comment by afuerhoff** [comment]
Controller is not stopped. It happens nothing

**Comment by afuerhoff** [comment]
Hi, I updated my system to 20.17.0 and after a restart the update runs without problems. 
I will close the issue.

**Comment by foxriver76** [comment]
Nice, that it works again in the end it seems this systemd call somehow failed https://github.com/ioBroker/ioBroker.js-controller/blob/1b8ad67b528d1e7fc54976044f272f20f80461c8/packages/controller/src/main.ts#L5772-L5786

We can check if we somehow can get log in such situations, because we need to detach the process completely so it survices a controller stop we cannot stream the logs here.
