### ISSUE TITLE
iobroker del mqtt also deletes mqtt-client

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.js-controller#320]
As the title says, when removing the MQTT broker, the client-Adapter is deleted too.

wondering why during deinstallation the log tells:
`$ ./iobroker del mqtt
Delete adapter "mqtt"
host.MQTT-Tinker Counted 2 instances of mqtt
host.MQTT-Tinker Counted 2 adapters for mqtt
host.MQTT-Tinker Counted 1 channels of mqtt
host.MQTT-Tinker Counted 537 states of mqtt
host.MQTT-Tinker Counted 117 states (io.mqtt.*) from states
host.MQTT-Tinker Counted 8 states (system.adapter.mqtt.*) from states
host.MQTT-Tinker Deleting 542 object(s).
host.MQTT-Tinker: Only 400 objects left to be deleted.
host.MQTT-Tinker: Only 200 objects left to be deleted.
host.MQTT-Tinker Deleting 125 state(s).
npm uninstall iobroker.mqtt --silent --save --prefix "/opt/iobroker" (System call)`

counted 2 instances and adapters I realised the issue afterwards when the mqtt-client was deinstalled too.

**Comment by AlCalzone** [comment]
The problem is due to two things:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupInstall.js#L1045
`enumerateAdapters` and `enumerateAdapterInstances` work by generating an object view with the start key `system.adapter.${adapter}` and the end key `system.adapter.${adapter}.\u9999`.

In https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemServer.js#L2743
```js
            if (params) {
                if (params.startkey && id < params.startkey) continue;
                if (params.endkey   && id > params.endkey)   continue;
}
```
the filtering is done by comparing strings logically (greater or smaller). Now, there's the problem that `system.adapter.mqtt-client` is greater than `system.adapter.mqtt.\u9999` because `"-" < "."`, which means mqtt-client is included in the list.

We need to do the enumeration like `enumerateAdapterDevices` where a RegExp is used to test the object IDs:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupInstall.js#L1165

**Comment by GermanBluefox** [comment]
Fixed?

**Comment by Apollon77** [comment]
I would add it to 2.0.0 project with the testing flag
