### ISSUE TITLE
Improved handling of connection errors

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.js-controller#403]
When a slave looses the connection to the master controller it stops all adapters. I assume this is for safety reasons so that no changes are lost.
It would be much better if the slave is able to buffer changes for some time so that short connection drops (i.e. slave connected via wlan) can be handled gracefully.
In my case I have zwave and zigbee running on a slave and it is quite some effort to start the adapters again when the network connection has a short hick-up.

**Comment by Apollon77** [comment]
We will not change anything here for 1.5.x because js.controller 2.x will contain a complete rewrite for the state/object databases and so is working completely different.
js.controller 2.0 could be installed from GitHub maste rdirectly but not yet stable ... but you can give it a try (or wait till we publish officially)

I close here, please reopen/recreate if after 2.0 release it is the same. Then with logs of such a problem please.
