### ISSUE TITLE
Greenlock v2 End of Life: Action Required

### ISSUE THREAD

**Issue by coolaj86** [ioBroker/ioBroker.js-controller#439]
Hello friends,

Greenlock v2 (Let's Encrypt / ACME client) has reached end-of-life and is will stop working this October.

The next version is in the works with lots of bug fixes, better error handling and logging.

I'd love your support for Greenlock v3 so that I can give you time to update, integrate, and test:
https://indiegogo.com/at/greenlock

**Comment by Apollon77** [comment]
@solderjs We got your message. Only for us as a open source project it's hard to support ... 

But one other thing: Could you please have a look at this: https://git.coolaj86.com/coolaj86/greenlock.js/issues/44

**Comment by solderjs** [comment]
Understood about not having funding. Something needs to change in Open Source so that projects can get support. Everyone I talk to that has a popular project is having the same problems in this regard.

I just took a quick look on my Win 10 machine... and I'm baffled.

It runs as expected (more or less) when I run it manually:

```
node node_modules\acme-v2.js\scripts\postinstall
```

However, when run by the npm runner it opens up `package.main` in Visual Studio Code. I'm wondering if it's related to https://github.com/npm/cli/commit/aa22ff6ea28dcb17e9f2b1bc87f2a4b5b868bf8a

I'll dig around a bit more later today.

**Comment by solderjs** [comment]
Found the problem. It is a bug in `cmd-shim` and I'll publish the update later today:

https://github.com/npm/cmd-shim/issues/40

**Comment by Apollon77** [comment]
@solderjs please send me a short info on iobroker@fischer-ka.de ... want to discuss an idea with you regarding the visibility/funding topic. 

And for support we can try to support you with testing for sure.

**Comment by solderjs** [comment]
I updated acme-v2 and synced the latest patch versions of greenlock-express/greenlock/acme/acme-v2.

If you update to latest your Windows tests should pass again.

**Comment by solderjs** [comment]
Also: I just sent you an email.

**Comment by Apollon77** [comment]
Thank you for the fast fix. Will check once back home. Also answered your email.

**Comment by raintonr** [comment]
I have been looking at this and seems there are choices to be made regarding how to implement following versions of Greenlock.

Looking at their examples from `greenlock-express`, seems one can either initialise the Greenlock module, passing a callback that then fires and can utilise the created server...

https://git.rootprojects.org/root/greenlock-express.js/src/branch/master/examples/https/server.js

... or one sets up their Express app first and passes that to the Greenlock module for it to use directly:

https://git.rootprojects.org/root/greenlock-express.js/src/branch/master/examples/express/server.js

Either way, this is looks completely incompatible with the way the controller `letsencrypt.js` works right now. There are probably other mechanisms but it's probably best to follow one of the examples of how the Greenlock authors envisaged this would work.

IMHO, if the web adapter is going to use Express and also Greenlock then the `letsencrypt.js` code inside js-controller should be retired and all relevant code should live within the web adapater. That being the case, doesn't this issue belong within that adapter's codebase?

**Comment by Apollon77** [comment]
It is not just web, also admin allows to offer "the server" and also some others - basically each adapter that offers a webserver port can initialize that ( at least from why I know/see)

But when checking that one example ... is https://git.rootprojects.org/root/greenlock-express.js/src/branch/master/examples/https/server.js#L29 not exactly the "raw https server" letsencrypt.js already returns right now?

**Comment by GermanBluefox** [comment]
As @Apollon77 said, for me the second example looks compatible with current solution.

**Comment by raintonr** [comment]
Well, this Express solution looks promising, but the problem is one either writes config information entered in the IOB admin settings to JSON files (which sounds like a bodge) or... 

> How to use JavaScript configuration?
> You don't. It's JSON on purpose.
> ...
> If you have a dynamic or advanced use case (i.e. you need stuff in a database, or to change config on-the-fly), you can use the Greenlock API (not Greenlock Express) and you'll love it.

https://git.rootprojects.org/root/greenlock-express.js#2-how-to-use-javascript-configuration

Having looked at Greenlock API can assure you I do not love it! Just need to spend more time to fully understand it maybe?
