### ISSUE TITLE
Objects in redis needs some more CPU then without ... how to optimize?

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#477]
Reason is easy: All the JSON.parse and stringify for all Object operations AND that objects are read for each state access

Ideas could be caching in general ... question is how best?
* cache for all read/write objects and subscribe to them to have the cache updated (full blown solution, pot. cache expiry to clean up some memory because will be stored per adapter process)
* rewrite state/right check logic to use a special method and only cache the rights-check relevant parts. Means: All normal object read/write would still go through to the DB, but only rights are cached/subscribed to update
* optimize for "JSON.parse" to store the String and objectand after reading an object doing a string check and if an object is already known for this string use the already parsed object to return (but clone) ... don't know if the effect is that great here ...
* accept it as is :-)

**Comment by AlCalzone** [comment]
Questions we need to ask ourselves:
* how often do we use parse/stringify during that process? I've done a quick code search with github and found several locations where objects are cloned using parse(stringify). Since those methods block the event loop, this can become a performance bottleneck: https://medium.com/ft-product-technology/this-one-line-of-javascript-made-ft-com-10-times-slower-5afb02bfd93f
* Do we need to read the entire object every time?
* Is it possible to do the caching in one location? Or is it possible that several processes have an active connection to redis and change the objects without another process knowing?
* Can we do other optimizations? E.g. here you stringify the same object twice in a row: https://github.com/ioBroker/ioBroker.js-controller/blob/67b32eec3ffd8b0f685670397c7ab6ce22a510f4/lib/redisHandler.js#L86

**Comment by Apollon77** [comment]
1.) Ideally only once (read from redis ... parse ... return ... and yes in some cases clone (but there should be more rare cases), but it is once. The "In mem DB" has the whole objects already parsed in mem and simply returns them (maybe after a clone)
2.) No, We mainly have two use cases: rights check and full object ... thats why the idea above. We also could store rights data and full object in parallel and then access the needed entity. Then we "just" need something transactional on write (https://redis.io/topics/transactions) Could mybe also optimize a bit for rights checks
3.) Each adapter process have their own Connections to the Redis and each process can change data, so yes objects could be written from all processes in parallel. This could be solved by an additional "publish" with "subscribe" but this is async ...
4.) This location is "as designed" and behind a normally NOT set flag - this flag is there for "extensive debugging needs" and so not problematic in a normal use cases .. . (and when i need protocol level debug then performance can not matter ;-) )

**Comment by AlCalzone** [comment]
Could we make use of this https://redislabs.com/blog/redis-as-a-json-store/ ?
Then the rights lookup could simply be another command to redis.

**Comment by Apollon77** [comment]
Problem: It is an own executable, so this is not available in the package depos for OSses and such :-(

**Comment by AlCalzone** [comment]
Ok, next idea: https://redislabs.com/ebook/part-1-getting-started/chapter-1-getting-to-know-redis/1-2-what-redis-data-structures-look-like/1-2-4-hashes-in-redis/
Store each ioBroker object as a hash. Each top level key/property either has a primitive value or is stored as a JSON string.

**Comment by Apollon77** [comment]
Needs research

**Comment by foxriver76** [comment]
hashes are very unhandy for nested objects

**Comment by Apollon77** [comment]
I would leave it as is and try to use other options to optimize JSON parsing and such ... else it is as it is

**Comment by foxriver76** [comment]
So close?
