### ISSUE TITLE
Remove adapter.getMessage

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#575]
... and fix the following Adapters before:

* ...frankjoke mehrere
* ioBroker.discovery
* ioBroker.email ?
* ioBroker.hmm
* ioBroker.megad
* ioBroker.megadd
* ioBroker.megaesp
* ioBroker.mqtt
* ioBroker.node-red
* ioBroker.noolite
* ioBroker.opcua
* ioBroker.owfs
* ioBroker.ping
* ioBroker.pushover ?
* ioBroker.pushsafer
* ioBroker.sayit
* ioBroker.snips
* ioBroker.telegram --> 1.4.7+
* ioBroker.wrapper
* ioBroker.zigbee
* ioBroker.zont
* iobroker.km200

**Comment by Apollon77** [comment]
Status 12.3.2020

* hmm
* megad
* megadd
* megaesp
* pushsafer
* sayit
* snips
* frankjoke (damit ggf radar2, systeminfo, broadlink2...)
* wrapper

**Comment by foxriver76** [comment]
sayit has it removed now but 1.9.1 needs npm publish

**Comment by Apollon77** [comment]
Ok, updates Status (based on Github):

Left are:
* hmm
* megad
* megadd
* megaesp
* pushsafer
* snips
* frankjoke (damit ggf radar2, systeminfo, broadlink2...)
* wrapper

**Comment by Apollon77** [comment]
Move deprecation to 3.1 in 6 months?

**Comment by foxriver76** [comment]
Yes. We should try to get access to frankjoe stuff in the meantime

**Comment by Apollon77** [comment]
I move that ticket to controller 3.1 to give us some ore time - I move after updating logging

**Comment by foxriver76** [comment]
AFAIK @frankjoke is active again. So any updates according to the list, so we can finally remove it in 3.2? ;-)

**Comment by frankjoke** [comment]
Ok, what's up? adapter.getMessage should not be used anymore? what is the migration strategy?

I use myAdapter for nearly all my adapters and this makes all the basic interface. I am requriting is and the test of new version is already in radar2 V2. It would be great to know what I need to change in addition.

**Comment by frankjoke** [comment]
@Apollon77 
Ingo, I used already "@iobroker/adapter-core": "^2.4.0" but I am very unhappy with it. The reasoin is that you can't include it normally because if no ioBroker (js-controller) is available it kills the load of the adapter. This is not good because in testing and debugging I started the adapter in the past without ioBroker! Also test runs with Mocha and so on are not so easy to generate because you always need to run it from iobroker environment. Can you change this in future versions? It would amke our live testing and debugging adapter funktion much easier!

**Comment by foxriver76** [comment]
@frankjoke getMessage is doing absolutely nothing for some time now. So just remove it from your code - nothing to migrate ;-)

For the other question @AlCalzone is your man.

**Comment by AlCalzone** [comment]
@frankjoke Do you have an example of a test that is not working outside of the iobroker environment because of adapter-core?

**Comment by frankjoke** [comment]
@AlCalzone 
Most of my adapters interface with some devices or services and in the past I used just VS-CODE on my development system to start/run the adapter from local directory with node with debug if I do not test iobroker-Topics. This is 90% of my testing and debugging because I need iobroker only for writing finaly states or adopting config.
 
All the devices where iobroker is running are remote and I need to copy changes to the node_modules... before starting a test on these machines with ioBroker.

Now by using the acore.Adapter class it crashes when loading outside of iobroker e´ven if I do not make an instance of it! 
In testing I do not create instance of adapter, just use MyAdapter  (my adapter wrapper) static functions to start main or do logs with console instead of iobroker.

**Comment by frankjoke** [comment]
You can use my acceptdata adapter (generated with iobroker adaptertool) https://github.com/frankjoke/ioBroker.acceptdata
It will super seed some time my systeminfo adapter but at the moment ist just used to store my weather station data instead sending it to WeatherUnderground. 
Even if you remove the `new Acceptdata();` you cannot run any code if `const utils = require("@iobroker/adapter-core");` is in the file because it dies not load completely ans states `Cannot find js-controller`.

before recent adapter-cores i could add test code before standard 
```
// @ts-ignore parent is a valid property on module
if (module.parent) {
  // Export the constructor in compact mode
  /**
   * @param {Partial<ioBroker.AdapterOptions>} [options={}]
   */
  module.exports = (options) => new Acceptdata(options);
} else {
  // otherwise start the instance directly
 new Acceptdata();
}
```
and comment out the `new Acceptdata();`  and run the adapter even including iobroker adapter file.

**Comment by AlCalzone** [comment]
Ok, you basically need a way to use adapter-core "lazy" (only when its actually needed). So if you don't create an instance of the adapter (new ... commented out) or use any of the exported tools, it should not run.
Did I understand correctly?

> and run the adapter even including iobroker adapter file

What do you mean by that? adapter.js is part of js-controller, so if you have that, adapter-core should find it.

**Comment by AlCalzone** [comment]
I've looked into this some more. What you need to do is structure your main file the old-fashioned way:
![grafik](https://user-images.githubusercontent.com/17641229/84566491-d2eeda80-ad71-11ea-9bc7-e5d58a1ebd9d.png)
This allows you to move `require("@iobroker/adapter-core")` into the adapter initialization routine which you want to comment out for your tests. I've created https://github.com/frankjoke/ioBroker.acceptdata/pull/1 to show you how.

**Comment by frankjoke** [comment]
@foxriver76 , Ok, I had it there because 3-4 years ago when I started to write adapters it was part of the 'eyample adapter' on which I built mine.

Will remove it from myAdapter and update adapters in next days.

@AlCalzone ,  You are right with your assumption in first post, will check your proposal to see if I can get it working.

**Comment by foxriver76** [comment]
@Apollon77 could you run another grep?
