### ISSUE TITLE
osDependencies technique needs to install via sudo

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.js-controller#599]
At least  here https://github.com/ioBroker/ioBroker.js-controller/blob/7610a609b2cfbec7e4abc4e4b94d8e4b9912a835/lib/setup/setupPacketManager.js#L158 sudo is required. Also we added apt etc. to the sudoers file, we still need to use sudo - it just prevents from asking for a password when using the command via sudo.

**Comment by AlCalzone** [comment]
And we might need to check if `sudo` is installed. Newer installer versions do this, but we cannot be sure.

**Comment by AlCalzone** [comment]
And we also need to check if the `iobroker` user may run the given command without requiring a password (or the exec command will get stuck in a password prompt). Here's how to do that:
```
sudo -n <command>
```
has an exit code of 0 if the user has sudo access without a password, otherwise it exits with 1.
Choose `<command>` in a way that the call does not do anything. For example, `apt -v` (I think)

**Comment by Apollon77** [comment]
fixed by @GermanBluefox via https://github.com/ioBroker/ioBroker.js-controller/commit/d4e067464c0f32c444be81825ed5a3784c099c56
