### ISSUE TITLE
Delete uploaded adapter files on adapter delete

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#651]
Make sure nothing stays there. Eg flot uploaded Web stufff

**Comment by smartboart** [comment]
might be the same problem with other adapters too...deleted time and weather widget and Wetter widget Adapter, but all widgets are still available...

**Comment by foxriver76** [comment]
Is there more stuff to delete than `<adapter>.admin` folder, and potentially `/vis/widgets/<adapter>.html` and` /vis/widgets/<adapter>` folder if existing?

**Comment by Apollon77** [comment]
Yes ... there also could be "meta" folders defined by the adapter ... e.g. like https://github.com/sbormann/ioBroker.iqontrol/blob/master/io-package.json#L759 ... so basically getObjectView with meta and "adaptername" as start !?

But you need to use the iobroker own functions to delete that stuff so recursive objects.readDir and such

**Comment by foxriver76** [comment]
Thats clear, because object redis.. for the common files like widgets which also play a special role, we could probably simply enhance the array https://github.com/ioBroker/ioBroker.js-controller/blob/555cadfc7302b8ec48378739517e6443b419f9a6/lib/setup/setupInstall.js#L1507 but it seems like I can't use a folder structure here, because `sanitizePath` https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemFileDB.js#L607 removes all folder structure information, by replacing `//` and `\`.. what are best practices to get it working? Unfortunately, JSDoc is also missing at https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L4142 where the same structure is needed..

And meta as mentioned by you have to be handled in a more specific way.

**Comment by Apollon77** [comment]
in the methods the first parameter is the "adapter/meta objectname", so "vis" or "bla.admin" o "iqontrol.meta" and second parameter is the path inside this basic directory

**Comment by foxriver76** [comment]
Makes sense, but widgets don't have a corresponding id haven't they?

**Comment by foxriver76** [comment]
At least grepping for them in my files objects db doesn't show anything .. ;-)

**Comment by Apollon77** [comment]
widget files are incorporated into the vis stuff when I know correctly. This happens on upload/start of vis

**Comment by Apollon77** [comment]
so widgets are as you wrote above inside vis "bucket" in a sub path

**Comment by foxriver76** [comment]
ah found it in vis/_data.json

**Comment by foxriver76** [comment]
Hm so probably it would need extra logic besides just removing the files.. it will be necessary to delete the information from _data.json too?
