### ISSUE TITLE
Suppress log message "at least one host is running" for systems without multihost

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#657]
I'm talking about this:
```
$ iobroker status
iobroker is running on this host.

At least one iobroker host is running.
```

If I am on a single-host system, the first message implies the 2nd one. This is redundant information and confuses users.
Actually, I'm not even sure if the 2nd message is easily understood by users with a multihost. Could we print here *which* host is running?

**Comment by Apollon77** [comment]
This info all relies on the "alive" states of hosts and if the DBs are available or were opened by the status CLI command (then iobroker is considered not running on any host).

In fact work here would be to use "is js-controller proces running" check for one info and DB availabel for other ... or really list all hosts and their status and not current host only ...

And really say about where the DB is connected and which format

**Comment by AlCalzone** [comment]
1. Do you agree that we don't need two messages in a single-host environment?
2. Do you agree that the 2nd message is not very clear to a user that does not know these specifics you wrote

**Comment by Apollon77** [comment]
Hm ... Difficult :-)

I kind of agree to the following change in the logic here:
* We need one message which checks if a js-controller process is running on the current host where the command is executed on.
* We need a second message that pot. tells that the database is active and existing (could be an other - master - host or a redis instance)
* We could select the available hosts and if there is really only one AND matches to the current hostname AND it is a file-DB then the second message could be not shown because the first one should be enough.
* There might be other cases to check where it makes sense.

In general my idea would be
* First Line check for priocess on current host and tells if js.controller process is run ing on this host
* (if DB is online) we list all hosts in the DB with their Alive-Status
* (if DB is offline) we tell that the database is unavailable (this one could be not shown if we find it being a single-host system)

**Comment by AlCalzone** [comment]
The general idea sounds good. But I would especially suppress the message for connected hosts in a single host system.
If the current host is connected, that is all a user needs to know and vice versa.

**Comment by Apollon77** [comment]
I agree. The check would be like: (DB-type is file && ip is 0.0.0.0 or 127.0.0.1 or current IP) or (redis && ip 127.0.0.1 or current ip) and the only existing host is the current one
