### ISSUE TITLE
Adjust Certificate livetime and recalculation logic 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#684]
https://www.heise.de/mac-and-i/meldung/Verkuerzte-Laufzeit-fuer-SSL-TLS-Zertifikate-Apple-prescht-offenbar-vor-4666010.html?wt_mc=nl.red.ho.ho-nl-daily.2020-02-22.link.link

**Comment by Stabilostick** [comment]
<s>
Please reduce the maximum certificate duration to 29 hours. This increases the security enormously, because it reduces the time window for attacks even more.
Also it is much easier for admins to remember if they have to renew the certificate every day than if they only do it once a year.

An additional plus: The admin must then also take care of the servers on Sundays and holidays. After all, attacks are just as frequent on Sundays, so you should not be less vigilant than on weekdays.

Translated with www.DeepL.com/Translator (free version)
</s>

**Comment by Apollon77** [comment]
Lol

**Comment by Apollon77** [comment]
TODO: CHeck readme
