### ISSUE TITLE
iobroker.js r vis => "vis-colorpicker.0", "vis.0".

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#722]
C:\pWork>node node_modules/iobroker.js-controller/iobroker.js r vis
The adapter "vis" has multiple instances! Please specify which one should be started: "vis-colorpicker.0", "vis.0".

**Comment by Apollon77** [comment]
r === restart

Which js-controller?

**Comment by foxriver76** [comment]
So I guess fixed with https://github.com/ioBroker/ioBroker.js-controller/commit/63d611d7f5b72d3007e8a1bb37e3358d021e36c4? However, I've tried it with https://github.com/ioBroker/ioBroker.js-controller/commit/555cadfc7302b8ec48378739517e6443b419f9a6 having `vis.0` and `vis-colorpicker.0` instances installed, but couldn't replicate the described behaviour.

**Comment by Apollon77** [comment]
Then we should get a retest with 3.0 :-)
