### ISSUE TITLE
Make sure instanceObjects are updated in system-adapter.(*).* objects and used from there

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#769]
On Adapter updates the instanceObjects are not updated in the objects. The adapter process is reading io-package to get the current infos from there. We should change that and also use the object here.

We also should change where else io-package.json is used directly in main.js or adapter.js

**Comment by foxriver76** [comment]
`instanceObjects` are uploaded since https://github.com/foxriver76/ioBroker.js-controller/commit/68f3e8212dfccb2687d1e9443b16a4921aa4f1a9 but still used in adapter.js e. g. https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/adapter.js#L1378 and many more

**Comment by Apollon77** [comment]
lets optimize that in 3.2
