### ISSUE TITLE
MTBF and MTTR

### ISSUE THREAD

**Issue by Sebastian-G** [ioBroker/ioBroker.js-controller#960]
We are currently investigating home automation systems as part of a research project. 
Have parameters such as MTBF and MTTR already been determined?

**Comment by Apollon77** [comment]
We do not collect or protocol such values. But in fact since js-controller 3.0 we included sentry error/crash reporting. if the users allow that reporting we get Infos on crashes and so we can react with fixes and Webapps have a „feeling“ about crash rates. 

The challenge for these values you are interested in in my eyes for a system like iobroker are about:
* iobroker is installed on systems with Linux, macOS and Windows based systems and also in Docker and other environments. So we have basically no Control over these systems. What we currently see in Sentry on crashes is 99% based on problems with permissions,filesystem (especially runner out of space or bad filesystem because of as card topics on cheap hardware systems) and such topics where wenn’s the software providers do not have control. Do this should be calculated into MTBF or MTTR calculation? ;-) do where to draw the line?
* the system design is very modular because each adapter can run as single process. Are these calculated also in MTBF and MTTR? This is getting problematic because many adapter have external dependencies e.g. to cloud systems or local Interfaxes for devices (most undocumented by the producer).
* Same goes with adapters running in compact mode pot. Inside the controller process and so one adapter could crash the controller (risk of that vs memory usage ...)
* additionally we rely on the Lts versions of node.js and also several npm versions. Also here things are slightly different and is out of our control. 

Summarizing: we have a good idea of the quality and crash rates from iobroker own/ controllable parts and they are very low. Fixing ist mostly a restart.

We try with providing an installer/Fixer to produce some more „comparable systems“, but it is still very flexible. 

So what exactly you would be interested in?!

**Comment by Sebastian-G** [comment]
> Summarizing: we have a good idea of the quality and crash rates from iobroker own/ controllable parts, especially the js-Controller and they are very very low. Fixing an error mostly a restart - and this is mostly done automatic, so the time till it runs again is very short.

We are aware that ioBroker can be influenced by external circumstances.

I think we can already live with this statement 😄

**Comment by Apollon77** [comment]
You‘re welcome. If you want to know more details just contact me via email to ingo.fischer@iobroker.net
