### ISSUE TITLE
Detect "deamon" Adapter Restart Loops

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#961]
We currently have the problem that if an adapter crashes "shortly after start" that will produce an infinitive loop of restarts.
When I remember correctly we should be able to detect such "start errors" right now if the "alive" flag of the adapter is never set (or we were able to do that but lost it in last updates), but as soon as this crash comes a bit delayed we have no chance.

Ideas could be:
* to check that adapter process runs longer then x (60?) seconds? If not count as crash
* to introduce a new error code (or do we have one?) if an Adapter ended with an exception/unhandled promise and only count these when within x (60?) seconds after process start

If such a "crash restart loop" is sdetected we should givbe the adapter 3 tries and disable the adapter afterwards

**Comment by AlCalzone** [comment]
Spontaneous idea:
* If an adapter crashes and not because of NODE_MODULES_VERSION mismatch, remember the error message and when it happened
* If the adapter crashes again within say 60 seconds, check the error message. The wait time between restarts and loading the adapter should not be included in this time IMO.
* If the error message is the same, we can safely assume it won't fix itself and disable it immediately. If the error message is not the same, I guess disabling it after 3 consecutive crashes is fine.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/pull/1129
